import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
opacity = 0.8
blur = false

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
size = 12

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
