import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

live_config_reload = true

[env]
term = "xterm-256color"

[window]
opacity = 0.8
blur = false

decorations = "Full"

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
size = 12

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
