return {
    { "akinsho/bufferline.nvim", enabled = false },
    { "folke/flash.nvim", enabled = false },
    -- { "folke/lazydev.nvim", enabled = false },
    { "folke/todo-comments.nvim", enabled = false },
    { "folke/trouble.nvim", enabled = false },
    { "gitsigns.nvim", enabled = false },
    { "lewis6991/gitsigns.nvim", enabled = false },
    -- { "lukas-reineke/indent-blankline.nvim", enabled = false },
    { "MagicDuck/grug-far.nvim", enabled = false },
    { "nvim-mini/mini.ai", enabled = false },
    { "nvim-mini/mini.nvim", enabled = false },
    -- { "nvim-mini/mini.indentscope", enabled = false },
    { "nvim-mini/mini.pairs", enabled = false },
    { "windwp/nvim-ts-autotag", enabled = false },
}
